### ISSUE TITLE
functions: line 162: ed: command not found

### ISSUE THREAD

**Issue by ben29** [waja/maldetect#11]
when i run:
/usr/local/maldetect/maldet -d
i get this error:

> /usr/local/maldetect/internals/functions: line 162: ed: command not found
> maldet(14527): {update} checking for available updates...
> /usr/local/maldetect/internals/functions: line 162: ed: command not found
> maldet(14527): {update} hashing install files and checking against server...
> /usr/local/maldetect/internals/functions: line 162: ed: command not found
> maldet(14527): {update} latest version already installed.

i didn't edit this file

**Comment by szepeviktor** [comment]
Try installing `ed`.
It is an essential file on Linux distros.

**Comment by ben29** [comment]
i install it now..
but 7 days i using this command without any error..

**Comment by waja** [comment]
@ben29 this is not the origin project of maldetect, but about the Debian packaging. I recommend to use https://github.com/rfxn/linux-malware-detect.  
If you use Debian (or Ubuntu or Debian based Distro) feel free to use the Debian packages at https://github.com/waja/maldetect/releases.
