### ISSUE TITLE
Please include packaging instructions

### ISSUE THREAD

**Issue by szepeviktor** [waja/maldetect#12]
```bash
wget https://github.com/waja/maldetect/archive/rework.zip
unzip rework.zip

wget https://github.com/rfxn/linux-malware-detect/archive/1.5.1.tar.gz
mv 1.5.1.tar.gz maldetect_1.5.1-pre2.orig.tar.gz

cd maldetect-rework/
dpkg-buildpackage -uc -us && echo "OK."
```

**Comment by waja** [comment]
Sorry, but for people who want to build their packages from source, I expect them to find documentations like https://wiki.debian.org/BuildingTutorial#Rebuild_without_changes via preferred search engine.

All others can grab binary packages from https://github.com/waja/maldetect/releases actually.

**Comment by szepeviktor** [comment]
ok-ok.
