### ISSUE TITLE
Unable to build debian package

### ISSUE THREAD

**Issue by PSiAU** [waja/maldetect#4]
Thank you for starting to maintain this again :)
I'm trying to build the debian package but i'm getting an error during the build process:
git-buildpackage -uc -us
dh clean
   dh_testdir
   dh_auto_clean
   dh_clean
fatal: Not a valid object name upstream/1.4.2+dfsg

**Comment by waja** [comment]
Looks like you are missing the tag "upstream/1.4.2+dfsg", which is needed to create your upstream source tarball. Anyway ... did you install the dependencies yet?

**Comment by PSiAU** [comment]
Yep the dependencies are in place and installed with "sudo apt-get install git-core git-buildpackage", if that's what you mean.

**Comment by waja** [comment]
The build-dependencies are defined in https://github.com/waja/maldetect/blob/master/debian/control#L5.

Anyway ... I forgot to push the tag "upstream/1.4.2+dfsg", which I've done some seconds ago. Just give it a try!

**Comment by PSiAU** [comment]
It works! Woohoo!
Thanks again Jan :)
