### ISSUE TITLE
Version 1.5 is available

### ISSUE THREAD

**Issue by waja** [waja/maldetect#6]
https://github.com/rfxn/linux-malware-detect/releases/tag/1.5

Diff: https://github.com/rfxn/linux-malware-detect/compare/1.4.2...1.5
Changelog: https://github.com/rfxn/linux-malware-detect/blob/master/CHANGELOG.RELEASE

**Comment by waja** [comment]
- default docroots removed from cron.daily: https://github.com/rfxn/linux-malware-detect/commit/8cc9c404a0bd13224e13bf3cae78ec55cbd1424c

**Comment by waja** [comment]
This was fixed by 7c0dba1917f315ccfdec509bab7bd4fe38105142

**Comment by szepeviktor** [comment]
When will the rework branch be released?

**Comment by waja** [comment]
> When will the rework branch be released?

When 1.5.1 is released finaly.

**Comment by waja** [comment]
> > When will the rework branch be released?
>
> When 1.5.1 is released finaly.

The latest 1.5 release can be grabbed via https://github.com/waja/maldetect/tree/debian/1.5-1 or https://github.com/waja/maldetect/releases/tag/debian%2F1.5-1
